language: go
go: 1.6
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.m2
before_install:
  - sudo apt-get update
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=1.11.0-0~trusty
install:
  - docker version
  - build/vendor.sh
script:
  - make all
  - sudo chown -R ${USER}:${USER} bundles
  - ( cd scm/bitbucket/hooks; mvn clean package )
after_success:
  - build/.build-images.sh
