language: go
go: 1.6
sudo: required
services:
  - docker
cache:
  directories:
    - $HOME/.m2
install:
  - docker version
  - build/vendor.sh
script:
  - make all
  - sudo chown -R ${USER}:${USER} bundles
  - ( cd scm/bitbucket/hooks; mvn clean package )
after_success:
  - build/.build-images.sh
